### ISSUE TITLE
Use lambada in Windows 10 x64

### ISSUE THREAD

**Issue by Samaneh1981** [hybridLambda/hybrid-Lambda#29]
Hi dear
I have Windows 10 x64 on my laptop.
Is there any compatible C++ compiler that I use it?
If not, is there a pre installed Linux virtual machine (VMWare) that I use it without full installation of Linux? I mean something like TurnKeyLinux (www.turnkeylinux.org)
If not, which version of Debian Linux need to  install on VMWare to use this code?
Thank you,

**Comment by shajoezhu** [comment]
Hi there

I'd suggest to use virtual box, and install ubuntu. The installation should be quite straightforward.

Best
Joe
